

# Site settings
title: Project. __ Junho Park
email: cnaa97@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Junho Park is a Front-end Developer and Designer living and working in Seoul, South Korea.
  Park held a bachelor’s degree of Fine Arts, majored in Spatial Design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://junojunho.com"
linkedIn: "https://www.linkedin.com/in/cnaa97"
github: "https://github.com/cnaa97"

# Permalinks
permalink: /:categories/:title

twitter_username: cnaa97
github_username:  cnaa97

# Build settings
markdown: kramdown
assets:
  compress:
    - css: true
    - js: true

# Language
languages: ["ko", "en"]

# Plugins
plugins:
  - jekyll-paginate
paginate: 10

include: ['_pages']
